schema:
  - name: played_at
    type: TIMESTAMP
  - name: context
    type: RECORD
    fields:
      - {name: type, type: STRING}
      - {name: uri, type: STRING}
      - name: external_urls
        type: RECORD
        fields:
          - {name: spotify, type: STRING}
  - name: track
    type: RECORD
    fields:
      - {name: id, type: STRING}
      - {name: name, type: STRING}
      - {name: duration_ms, type: INTEGER}
      - {name: explicit, type: BOOLEAN}
      - {name: popularity, type: INTEGER}
      - {name: disc_number, type: INTEGER}
      - {name: track_number, type: INTEGER}
      - {name: is_local, type: BOOLEAN}
      - {name: uri, type: STRING}
      - name: external_ids
        type: RECORD
        fields:
          - {name: isrc, type: STRING}
      - name: external_urls
        type: RECORD
        fields:
          - {name: spotify, type: STRING}
      - name: artists
        type: RECORD
        mode: REPEATED
        fields:
          - {name: id, type: STRING}
          - {name: name, type: STRING}
          - {name: uri, type: STRING}
          - name: external_urls
            type: RECORD
            fields:
              - {name: spotify, type: STRING}
      - name: album
        type: RECORD
        fields:
          - {name: id, type: STRING}
          - {name: name, type: STRING}
          - {name: album_type, type: STRING}
          - {name: release_date, type: STRING}
          - {name: release_date_precision, type: STRING}
          - {name: total_tracks, type: INTEGER}
          - {name: uri, type: STRING}
          - name: external_urls
            type: RECORD
            fields:
              - {name: spotify, type: STRING}
          - name: images
            type: RECORD
            mode: REPEATED
            fields:
              - {name: url, type: STRING}
              - {name: height, type: INTEGER}
              - {name: width, type: INTEGER}
          - name: artists
            type: RECORD
            mode: REPEATED
            fields:
              - {name: id, type: STRING}
              - {name: name, type: STRING}
              - {name: uri, type: STRING}
              - name: external_urls
                type: RECORD
                fields:
                  - {name: spotify, type: STRING}
  - name: _ingested_at
    type: TIMESTAMP
